name: Superheros
version: ${project.version}
main: net.dohaw.superheros.SuperherosPlugin
api-version: 1.17

commands:
  superhero:
    description: "The base command for this plugin"
    aliases:
      - sh
      - superh